name: Scrape HIS Konstanz

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        architecture: "x64"

    - name: Setup Google Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: latest

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraping script
      run: python scraping_his_konstanz.py
