# .github/workflows/debug-python-version.yml
name: Debug Python Version

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Print Python version
        run: python --version
