name: Scrape HIS Konstanz

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        architecture: "x64"

    - name: Setup Google Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Überprüfe Google Chrome Installation
      run: |
        which google-chrome
        google-chrome --version

    - name: Install ChromeDriver for Chrome 136
      run: |
        DRIVER_VERSION=136.0.7103.113
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip"
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraping script
      run: python scraping_his_konstanz.py

    - name: Upload CSV als Artifact
      uses: actions/upload-artifact@v4
      with:
        name: konstanz-courses
        path: courses_w2024_Konstanz.csv
